#!/usr/bin/env bash

set -euo pipefail

root=$(git rev-parse --show-toplevel)
run() { "${root}/Taskfile" "$@"; }

pushd "${root}/tests/drafts"
trap popd EXIT

time for i in {145..150}; do
  run html2md \
    -i "https://mailchi.mp/deararchitects/${i}-dear-architects" \
    -s 'table.mcnImageCardBlock,table.mcnCaptionBlock' >"deararchitects/${i}.md"
done
